# Generated by Django 3.2.6 on 2023-09-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230902_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candle',
            old_name='CLOSE',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='candle',
            old_name='DATE',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='candle',
            old_name='HIGH',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='candle',
            old_name='LOW',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='candle',
            old_name='OPEN',
            new_name='open',
        ),
    ]
